# Generated by Django 3.2.15 on 2022-10-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_alter_enrolledpupil_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledpupil',
            name='school_email',
            field=models.EmailField(max_length=200),
        ),
    ]
