# Generated by Django 3.2.15 on 2022-10-05 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passport', '0005_auto_20221004_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_profile_image', models.ImageField(upload_to='')),
                ('my_name', models.CharField(max_length=200)),
                ('my_emergency_contact_one_name', models.CharField(default='', max_length=200)),
                ('my_emergency_contact_one_number', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('my_emergency_contact_two_name', models.CharField(default='', max_length=200)),
                ('my_emergency_contact_two_number', models.PositiveIntegerField(default=0)),
                ('my_date_of_birth', models.DateField(default='DD/MM/YY')),
                ('my_biography', models.TextField(max_length=600)),
                ('my_family', models.TextField(max_length=600)),
                ('my_likes', models.TextField(max_length=600)),
                ('my_dislikes', models.TextField(max_length=600)),
                ('my_strengths', models.TextField(max_length=600)),
                ('my_difficulties', models.TextField(max_length=600)),
                ('my_supports', models.TextField(max_length=600)),
                ('my_calming_measures', models.TextField(max_length=600)),
                ('my_communication_skills', models.TextField(max_length=600)),
                ('my_other_info', models.TextField(max_length=600)),
                ('my_family_image', models.ImageField(upload_to='')),
                ('my_hobby_image', models.ImageField(upload_to='')),
                ('my_additional_image', models.ImageField(upload_to='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
