# Generated by Django 3.2.15 on 2022-10-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0006_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='my_additional_image',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='my_family_image',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='my_hobby_image',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='my_profile_image',
        ),
    ]
