# Generated by Django 3.2.15 on 2022-10-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0007_auto_20221005_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=200)),
                ('pupil_id', models.PositiveIntegerField(default=0, unique=True)),
            ],
        ),
    ]
