# Generated by Django 3.2.15 on 2022-10-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0008_teacherverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='pupil_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='teacher_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
