# Generated by Django 3.2.15 on 2022-10-07 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passport', '0011_alter_teacherverify_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherVerify',
            new_name='VerifiedTeacher',
        ),
    ]
