# Generated by Django 3.2.15 on 2022-10-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0013_alter_verifiedteacher_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifiedTeacher',
        ),
    ]
