# Generated by Django 3.2.15 on 2022-09-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
