# Generated by Django 3.2.15 on 2022-09-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_newuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_type',
            field=models.CharField(max_length=100),
        ),
    ]
