# Generated by Django 3.2.15 on 2022-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_newuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_type',
            field=models.CharField(choices=[('pupil', 'pupil'), ('parent', 'parent'), ('teacher', 'teacher'), ('school', 'school')], max_length=20),
        ),
    ]
